
Running tests...

Bar:
[6 (5)ms]
	Free Test
	[5ms]
		Standard Top Level Checks:                 2;  Failures:  0  [Deep checks: 1]

******  Critical Failures:  1  ******


	Error -- Unexpected Exception:
	Throw after check

	Exception thrown after check completed
	Last Recorded Message:

	Phoney equality check
	[int]

	=======================================

Foo:
[4 (4)ms]
	Unit Test
	[4ms]
		Standard Top Level Checks:                 2;  Failures:  0  [Deep checks: 0]

******  Critical Failures:  1  ******


	Error -- Unexpected Exception:
	This is bad

	Exception thrown during last check
	Last Recorded Message:

	Throw during check
	[sequoia::testing::(anonymous namespace)::foo]

	=======================================


-----------Grand Totals-----------
[10 (9)ms]
	Standard Top Level Checks:                 4;  Failures:  0  [Deep checks: 1]
	Standard Performance Checks:               0;  Failures:  0
	False Negative Checks:                     0;  Failures:  0
	False Negative Performance Checks:         0;  Failures:  0
	False Positive Checks:                     0;  Failures:  0
	False Positive Performance Checks:         0;  Failures:  0

******  Critical Failures:  2  ******

