Tests/Core/DataStructures/PartitionedDataGenericTests.hpp, Line 66
pushing back to non-existent partition throws

Expected Exception Type:
[std::out_of_range]
partitioned_sequence::index0out of range

=======================================

