
Running tests, synchronously...

Suite:
[Execution Time: 209us]
	Standard Top Level Checks:                 1;  Failures:  0  [Deep checks: 0]

******  Critical Failures:  1  ******


	Error -- Unexpected Exception:
	Error

	Exception thrown before any checks performed in file
	/Users/oliver/sequoia/Tests/Free_Test.cpp

	=======================================


-----------Grand Totals-----------
[Total Run Time: 512us]
[Execution Time: 209us]
	Standard Top Level Checks:                 1;  Failures:  0  [Deep checks: 0]
	Standard Performance Checks:               0;  Failures:  0
	False Positive Checks:                     0;  Failures:  0
	False Positive Performance Checks:         0;  Failures:  0
	False Negative Checks:                     0;  Failures:  0
	False Negative Performance Checks:         0;  Failures:  0

******  Critical Failures:  1  ******


Running tests, synchronously...

Suite:
[Execution Time: 42.2us]

-----------Grand Totals-----------
[Total Run Time: 298us]
[Execution Time: 42.2us]
	Standard Top Level Checks:                 0;  Failures:  0
	Standard Performance Checks:               0;  Failures:  0
	False Positive Checks:                     0;  Failures:  0
	False Positive Performance Checks:         0;  Failures:  0
	False Negative Checks:                     0;  Failures:  0
	False Negative Performance Checks:         0;  Failures:  0

Instability detected in file "Free_Test.cpp"
Outcome frequencies:
[50.0%,50.0%]

--No failures--

vs.

	Error -- Unexpected Exception:
	Error

	Exception thrown before any checks performed in file
	/Users/oliver/sequoia/Tests/Free_Test.cpp

	=======================================

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
