
Running tests, synchronously...

Suite:
[Execution Time: 1.2ms]
	Standard Top Level Checks:                 1;  Failures:  0  [Deep checks: 0]

******  Critical Failures:  1  ******


	Error -- Unexpected Exception:
	Error

	Exception thrown before any checks performed in file
	C:/Users/olive/sequoia/Tests/Free_Test.cpp

	=======================================


-----------Grand Totals-----------
[Total Run Time: 2.95ms]
[Execution Time: 1.2ms]
	Standard Top Level Checks:                 1;  Failures:  0  [Deep checks: 0]
	Standard Performance Checks:               0;  Failures:  0
	False Positive Checks:                     0;  Failures:  0
	False Positive Performance Checks:         0;  Failures:  0
	False Negative Checks:                     0;  Failures:  0
	False Negative Performance Checks:         0;  Failures:  0

******  Critical Failures:  1  ******


Running tests, synchronously...

Suite:
[Execution Time: 597us]

-----------Grand Totals-----------
[Total Run Time: 2.04ms]
[Execution Time: 597us]
	Standard Top Level Checks:                 0;  Failures:  0
	Standard Performance Checks:               0;  Failures:  0
	False Positive Checks:                     0;  Failures:  0
	False Positive Performance Checks:         0;  Failures:  0
	False Negative Checks:                     0;  Failures:  0
	False Negative Performance Checks:         0;  Failures:  0

Instability detected in file "Free_Test.cpp"
Outcome frequencies:
[50%,50%]

--No failures--

vs.

	Error -- Unexpected Exception:
	Error

	Exception thrown before any checks performed in file
	C:/Users/olive/sequoia/Tests/Free_Test.cpp

	=======================================

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
